import type { Metadata } from "next";
import{Bowlby_One_SC,DM_Mono} from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const bowlby = Bowlby_One_SC({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-bowlby-one-sc",
  weight : "400"
  
});

const dmMono = DM_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-mono",
  weight : "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bowlby.variable} ${dmMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
